- .husky/pre-commit
- package.json
- yarn.lock
> chore: update pre-commit configuration

- composer.json
- composer.lock
> chore(force-release): update minimum stability of composer

- .husky/pre-commit
> chore: update pre-commit settings

- src/Agent/Builder/AgentFactory.php
- src/Agent/Utils/ForestSchema/SchemaEmitter.php
> fix: onboarding generate schema

- src/Agent/Builder/AgentFactory.php
- src/Agent/Routes/System/HealthCheck.php
- src/Agent/Utils/ForestSchema/SchemaEmitter.php
- src/Agent/functions.php
- src/DatasourceDoctrine/DoctrineDatasource.php
- tests/Agent/Auth/Oauth2/ForestResourceOwnerTest.php
- tests/Agent/Builder/AgentFactoryTest.php
- tests/Agent/Services/ForestSchemaInstrospectionTest.php
> fix(onboarding): create cache only if env secret was set

- src/Agent/Utils/QueryConverter.php
- tests/Agent/Utils/QueryConverterTest.php
> fix(query-converter): patch the query converter with mariadb and mysql

- src/Agent/Utils/ConditionTreeParser.php
- src/DatasourceCustomizer/Decorators/DecoratorsStack.php
- src/DatasourceCustomizer/Decorators/Empty/EmptyCollection.php
- tests/DatasourceCustomizer/Decorators/Empty/EmptyCollectionTest.php
> feat: add empty decorator 

- src/Agent/Builder/AgentFactory.php
- src/Agent/Routes/Resources/Count.php
- src/Agent/Routes/Resources/Related/CountRelated.php
- src/DatasourceCustomizer/CollectionCustomizer.php
- src/DatasourceCustomizer/Decorators/CollectionDecorator.php
- src/DatasourceCustomizer/Decorators/DecoratorsStack.php
- src/DatasourceCustomizer/Decorators/Schema/SchemaCollection.php
- src/DatasourceToolkit/CollectionMethods.php
- tests/Agent/Routes/Resources/CountTest.php
- tests/Agent/Routes/Resources/Related/CountRelatedTest.php
- tests/DatasourceCustomizer/CollectionCustomizerTest.php
- tests/DatasourceCustomizer/Decorators/Schema/SchemaCollectionTest.php
> feat: add schema decorator

- src/Agent/Utils/ForestSchema/GeneratorCollection.php
> fix(schema): sort actions by id and fields by name in the schema

- src/Agent/Routes/Actions/Actions.php
- src/Agent/Utils/ForestSchema/ForestActionValueConverter.php
- src/Agent/Utils/Id.php
- tests/Agent/Routes/Actions/ActionTest.php
> chore: add tests on action routes

- src/DatasourceCustomizer/Decorators/Computed/ComputedCollection.php
- src/DatasourceCustomizer/Decorators/DecoratorsStack.php
- src/DatasourceCustomizer/Decorators/Empty/EmptyCollection.php
- src/DatasourceCustomizer/Decorators/OperatorsReplace/OperatorsReplaceCollection.php
- src/DatasourceCustomizer/Decorators/Relation/RelationCollection.php
- src/DatasourceToolkit/Components/Query/ConditionTree/ConditionTreeEquivalent.php
> feat(operator): improve the operator equivalence behaviour

- src/DatasourceCustomizer/Decorators/Actions/ActionCollection.php
- src/DatasourceCustomizer/Decorators/Actions/Context/ActionContext.php
- src/DatasourceCustomizer/Decorators/Actions/Types/FieldType.php
- tests/DatasourceCustomizer/Decorators/Actions/ActionCollectionTest.php
- tests/DatasourceCustomizer/Decorators/Actions/Context/ActionContextTest.php
> feat(action): add missing getters on action context

- src/DatasourceCustomizer/CollectionCustomizer.php
- src/DatasourceCustomizer/Decorators/Segment/SegmentCollection.php
- tests/DatasourceCustomizer/Decorators/Segment/SegmentCollectionTest.php
> fix(segment): add collection customization context to the segment function definition

- src/Agent/Http/Router.php
- src/Agent/Routes/Charts/ApiChartCollection.php
- src/Agent/Routes/Charts/ApiChartDatasource.php
- tests/Agent/Http/RouterTest.php
- tests/Agent/Routes/Charts/ApiChartCollectionTest.php
- tests/Agent/Routes/Charts/ApiChartDatasourceTest.php
> fix(chart): fix response of api smart chart

- src/DatasourceCustomizer/Decorators/Computed/ComputedCollection.php
- src/DatasourceCustomizer/Decorators/Computed/ComputedDefinition.php
- src/DatasourceCustomizer/Decorators/Computed/Utils/ComputeField.php
- src/DatasourceCustomizer/Decorators/Search/SearchCollection.php
- tests/DatasourceCustomizer/Decorators/Computed/ComputedCollectionTest.php
- tests/DatasourceCustomizer/Decorators/Computed/Utils/ComputeFieldTest.php
- tests/DatasourceCustomizer/Decorators/Search/SearchCollectionTest.php
> feat(decorator): add context in closure function for search and computed field decorators

- src/Agent/Routes/Resources/Count.php
- src/Agent/Utils/QueryAggregate.php
- src/BaseDatasource/BaseCollection.php
- tests/Agent/Routes/Resources/CountTest.php
> fix(count): fix count response

- src/DatasourceCustomizer/CollectionCustomizer.php
- src/DatasourceCustomizer/Decorators/DecoratorsStack.php
- src/DatasourceCustomizer/Decorators/Empty/EmptyCollection.php
- src/DatasourceCustomizer/Decorators/RenameField/RenameFieldCollection.php
- src/DatasourceToolkit/Components/Query/Aggregation.php
- src/DatasourceToolkit/Schema/Relations/ManyRelationSchema.php
- src/DatasourceToolkit/Schema/Relations/ManyToManySchema.php
- src/DatasourceToolkit/Schema/Relations/SingleRelationSchema.php
- tests/DatasourceCustomizer/CollectionCustomizerTest.php
- tests/DatasourceCustomizer/Decorators/RenameField/RenameFieldCollectionTest.php
> feat(decorators): add rename field decorator 

- src/DatasourceCustomizer/CollectionCustomizer.php
- src/DatasourceCustomizer/Decorators/DecoratorsStack.php
- src/DatasourceCustomizer/Decorators/PublicationCollection/PublicationCollectionDecorator.php
- tests/DatasourceCustomizer/CollectionCustomizerTest.php
> feat(customizer): add remove field customizer

- src/Agent/Utils/ForestSchema/GeneratorField.php
- src/DatasourceCustomizer/CollectionCustomizer.php
- src/DatasourceCustomizer/DatasourceCustomizer.php
- src/DatasourceCustomizer/Decorators/Computed/ComputedDefinition.php
- src/DatasourceCustomizer/Plugins/AddExternalRelation.php
- src/DatasourceCustomizer/Plugins/ImportField.php
- src/DatasourceCustomizer/Plugins/Plugin.php
- src/DatasourceToolkit/Components/Query/ConditionTree/ConditionTreeEquivalent.php
- tests/DatasourceCustomizer/CollectionCustomizerTest.php
> feat: add plugins import field & add external relation support

- src/DatasourceCustomizer/CollectionCustomizer.php
- src/DatasourceCustomizer/Decorators/OperatorsEmulate/OperatorsEmulateCollection.php
- tests/DatasourceCustomizer/CollectionCustomizerTest.php
> feat(customizer): add emulate field filtering method

- src/Agent/Routes/Resources/Related/CountRelated.php
- src/Agent/Services/JsonApiResponse.php
- tests/Agent/Routes/Resources/Related/CountRelatedTest.php
> fix(response): add missing  available include relationships to the response

- .github/workflows/build.yml
- .releaserc.js
> fix: update monorepo github action config

- .github/workflows/build.yml
- .github/workflows/split.yml
- CHANGELOG.md
> feat: add split github action workflow (#61)

- .github/workflows/build.yml
- .github/workflows/split.yml
> feat: add checkout module to the split action

- .releaserc.js
- CHANGELOG.md
> chore: add semantic-release-slack-bot config

- packages/Agent/.github/ISSUE_TEMPLATE.md
- packages/Agent/.github/PULL_REQUEST_TEMPLATE.md
- packages/BaseDatasource/.github/ISSUE_TEMPLATE.md
- packages/BaseDatasource/.github/PULL_REQUEST_TEMPLATE.md
- packages/DatasourceCustomizer/.github/ISSUE_TEMPLATE.md
- packages/DatasourceCustomizer/.github/PULL_REQUEST_TEMPLATE.md
- packages/DatasourceDoctrine/.github/ISSUE_TEMPLATE.md
- packages/DatasourceDoctrine/.github/PULL_REQUEST_TEMPLATE.md
- packages/DatasourceDummy/.github/ISSUE_TEMPLATE.md
- packages/DatasourceDummy/.github/PULL_REQUEST_TEMPLATE.md
- packages/DatasourceToolkit/.github/ISSUE_TEMPLATE.md
- packages/DatasourceToolkit/.github/PULL_REQUEST_TEMPLATE.md
> chore: add issue and PR templates

- .husky/pre-commit
> fix: remove validation's monorepo on precommit

- packages/Agent/src/Services/Permissions.php
- tests/Pest.php
> fix: permission on CRUD actions when app is on debug mode

- .github/workflows/split.yml
> fix: configure github workflow for eloquent datasource

- .releaserc.js
- composer.json
- packages/Agent/composer.json
- packages/Agent/src/Builder/AgentFactory.php
- packages/Agent/src/Facades/Logger.php
- packages/Agent/src/Routes/Charts/ApiChartCollection.php
- packages/Agent/src/Routes/Charts/ApiChartDatasource.php
- packages/Agent/src/Services/LoggerServices.php
- packages/Agent/src/Services/Permissions.php
- packages/DatasourceDoctrine/src/DoctrineDatasource.php
- packages/DatasourceToolkit/src/Datasource.php
- tests/Agent/Builder/AgentFactoryTest.php
- tests/Agent/Services/LoggerServicesTest.php
- tests/DatasourceToolkit/Unit/DatasourceTest.php
> feat(logger): add a default logger and allow user to define a custom logger

- packages/Agent/src/Routes/Security/ScopeInvalidation.php
- tests/Agent/Routes/Security/ScopeInvalidationTest.php
> fix: cache name to be forget on scope invalidation

- packages/Agent/src/Services/SmartActionChecker.php
- tests/Agent/Services/PermissionsTest.php
- tests/Agent/Services/SmartActionCheckerTest.php
> fix(permissions): allow users to request approval

- composer.json
- packages/Agent/composer.json
> fix: dependency version of monolog

- packages/Agent/src/Routes/Resources/Related/ListingRelated.php
- tests/Agent/Routes/Resources/Related/ListingRelatedTest.php
> fix: user with permission on the relationship can export it

- packages/Agent/src/Auth/OAuth2/ForestProvider.php
- packages/Agent/src/Utils/ForestSchema/GeneratorAction.php
- packages/DatasourceCustomizer/src/Decorators/Actions/Context/ActionContext.php
- tests/Agent/Routes/Actions/ActionTest.php
- tests/DatasourceCustomizer/Decorators/Actions/Context/ActionContextTest.php
> fix(datasource-customizer): add hasFieldChanged function to handle change hook on this field

- packages/DatasourceCustomizer/src/Decorators/Actions/ActionCollection.php
- tests/DatasourceCustomizer/Decorators/Actions/ActionCollectionTest.php
> fix(datasource-customizer): fix smart action default value behavior

- packages/Agent/src/Routes/AbstractAuthenticatedRoute.php
- packages/Agent/src/Routes/Security/Authentication.php
- packages/Agent/src/Utils/Whitelist.php
- tests/Agent/Routes/System/AuthenticationTest.php
> fix: ipwhitelist to authenticate routes

- packages/Agent/src/Http/Exceptions/AuthenticationOpenIdClient.php
- packages/Agent/src/Http/ForestController.php
- packages/Agent/src/Routes/Security/Authentication.php
- tests/Agent/Http/ForestControllerTest.php
- tests/Agent/Routes/System/AuthenticationTest.php
> fix(authentication): return errors detail instead of generic error 500

- packages/Agent/src/Utils/ForestSchema/GeneratorAction.php
> fix(action): generate schema when action has static form

- packages/Agent/src/Http/ForestController.php
- packages/DatasourceCustomizer/src/Decorators/Actions/ResultBuilder.php
- tests/Agent/Http/ForestControllerTest.php
- tests/DatasourceCustomizer/Decorators/Actions/ActionCollectionTest.php
- tests/DatasourceCustomizer/Decorators/Actions/BaseActionTest.php
- tests/DatasourceCustomizer/Decorators/Actions/ResultBuilderTest.php
> feat(action): allow user to set a custom header on a action result

- package.json
- yarn.lock
> fix(security): patch semantic-release dependency vulnerabilities

- yarn.lock
> fix(security): patch http-cache-semantics dependency vulnerabilities

- package.json
- yarn.lock
> fix(security): patch semver dependency vulnerabilities

- .github/workflows/build.yml
> chore(build): fix release step

- packages/BaseDatasource/src/BaseCollection.php
> fix(introspection): set column as read only when it has autoincrement constraint

- packages/DatasourceEloquent/src/Utils/QueryBuilder.php
- packages/DatasourceEloquent/src/Utils/QueryConverter.php
- tests/DatasourceEloquent/Utils/QueryConverterTest.php
> fix(eloquent-datasource): replace table name by relation name when select relation field

- packages/Agent/composer.json
- packages/BaseDatasource/composer.json
- packages/DatasourceCustomizer/composer.json
- packages/DatasourceDoctrine/composer.json
- packages/DatasourceDummy/composer.json
- packages/DatasourceEloquent/composer.json
- packages/DatasourceToolkit/composer.json
> fix: update minimum packages version

- packages/BaseDatasource/src/BaseDatasource.php
- tests/BaseDatasource/BaseDatasourceTest.php
> fix(datasource): add missing port attribute

- packages/DatasourceCustomizer/src/Decorators/Write/WriteReplace/WriteReplaceCollection.php
- tests/DatasourceCustomizer/Decorators/Write/WriteReplace/WriteSimpleCollectionTest.php
> fix(writereplace): rewrite patch does not remove field with null value

- .releaserc.js
> fix: packages version

- .releaserc.js
> fix: version packages

- .releaserc.js
> fix: releaserc version packages

- packages/Agent/src/Builder/AgentFactory.php
- packages/Agent/src/Services/LoggerServices.php
- tests/TestCase.php
> fix:(agent): serialize agent with closure to put in cache

- composer.json
- packages/Agent/composer.json
> fix(composer): remove ext-apcu from dependencies

- packages/DatasourceEloquent/src/EloquentCollection.php
> fix(eloquent): ensure the model is available before creating a relationship

- packages/Agent/src/Serializer/JsonApiSerializer.php
- packages/Agent/src/Serializer/Transformers/BaseTransformer.php
- tests/Agent/Serializer/BaseTransformerTest.php
> fix(serializer): use primary key of  the foreign collection for serialize the data

- packages/Agent/src/Utils/ForestSchema/GeneratorAction.php
- packages/DatasourceCustomizer/src/Decorators/Actions/BaseFormElement.php
- packages/DatasourceCustomizer/src/Decorators/Actions/FormLayoutElement/HtmlBlockElement.php
- packages/DatasourceCustomizer/src/Decorators/Actions/FormLayoutElement/LayoutElement.php
- packages/DatasourceCustomizer/src/Decorators/Actions/FormLayoutElement/PageElement.php
- packages/DatasourceCustomizer/src/Decorators/Actions/FormLayoutElement/RowElement.php
- packages/DatasourceCustomizer/src/Decorators/Actions/FormLayoutElement/SeparatorElement.php
- packages/DatasourceToolkit/src/Components/Actions/ActionFieldFactory.php
- packages/DatasourceToolkit/src/Components/Actions/Layout/PageElement.php
- tests/Agent/Utils/ForestSchema/GeneratorActionTest.php
- tests/DatasourceCustomizer/Decorators/Actions/FormLayoutElement/LayoutElementTest.php
- tests/DatasourceCustomizer/Decorators/Actions/FormLayoutElement/PageElementTest.php
- tests/DatasourceToolkit/Unit/Components/Actions/ActionFIeldFactoryTest.php
> feat(form): add support of page layout element

- packages/Agent/src/Http/Router.php
- packages/Agent/src/Routes/Capabilities/Collections.php
- packages/Agent/src/Routes/Resources/Listing.php
- packages/Agent/src/Utils/ForestSchema/FrontendFilterable.php
- packages/Agent/src/Utils/ForestSchema/GeneratorField.php
- packages/DatasourceToolkit/src/Validations/ConditionTreeValidator.php
- tests/Agent/Http/RouterTest.php
- tests/Agent/Routes/Capabilities/CollectionsTest.php
- tests/Agent/Routes/Resources/ListingTest.php
- tests/Agent/Utils/ForestSchema/FrontendFilterableTest.php
- tests/Agent/Utils/QueryStringParserTest.php
- tests/DatasourceToolkit/Unit/Validations/ConditionTreeValidatorTest.php
> feat(capabilities): add new collections route

- packages/Agent/src/Services/SmartActionChecker.php
- tests/Agent/Routes/Actions/ActionTest.php
> fix(permission): get approval conditions by role id

- packages/DatasourceCustomizer/src/Decorators/RenameField/RenameFieldCollection.php
- packages/DatasourceToolkit/src/Schema/Relations/ManyRelationSchema.php
- packages/DatasourceToolkit/src/Schema/Relations/ManyToManySchema.php
- packages/DatasourceToolkit/src/Schema/Relations/SingleRelationSchema.php
- tests/DatasourceCustomizer/Decorators/RenameField/RenameFieldCollectionTest.php
> fix(rename decorator): properly map relation when renaming pk field

- .github/workflows/build.yml
- .github/workflows/split.yml
> ci: upgrade actions

- packages/DatasourceCustomizer/src/Decorators/DecoratorsStack.php
- packages/DatasourceCustomizer/src/Decorators/LazyJoin/LazyJoinCollection.php
- tests/DatasourceCustomizer/Decorators/LazyJoin/LazyJoinCollectionTest.php
> feat: add lazy join decorator to improve performance

- packages/Agent/src/Routes/Charts/Charts.php
- packages/DatasourceCustomizer/src/Decorators/Chart/ResultBuilder.php
- tests/Agent/Routes/Charts/ChartsTest.php
- tests/DatasourceCustomizer/Decorators/Chart/ResultBuilderTest.php
> fix(charts): properly format week of year

- packages/Agent/src/Auth/OAuth2/ForestProvider.php
- packages/Agent/src/Http/Exceptions/AuthenticationOpenIdClient.php
- packages/Agent/src/Http/ForestController.php
- packages/Agent/src/Routes/Security/Authentication.php
- tests/Agent/Http/ForestControllerTest.php
- tests/Agent/Routes/System/AuthenticationTest.php
> fix: proper raise of OpenIDConnect Exceptions
